/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Payments } from "./Payments";
export * as factories from "./factories";
export { Payments__factory } from "./factories/Payments__factory";
